name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sandbox-frontend'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          package: './frontend'

      - name: Deploy Backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sandbox-backend'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          package: './backend'