name: Deploy Node App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create .env file
        run: |
          echo CONNECTION_STRING=${{ secrets.CONNECTION_STRING }} >> .env
          echo MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }} >> .env
          echo MONGO_COLLECTION_NAME=${{ secrets.MONGO_COLLECTION_NAME }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env

      - name: Install dependencies
        run: npm install

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: sandbox-backend-bernalo
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          package: .
