name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy Frontend App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sandbox-frontend-bernalo'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          package: './frontend/build'

  deploy-backend:
    runs-on: ubuntu-latest
    needs: deploy-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Backend App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sandbox-backend-bernalo'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          package: './backend'